spring.application.name=backend

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/resilience?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=gopika2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Secret
app.jwtSecret=ResilienceSuperSecretKeyForJwtAuthenticationInThisDisasterSupportApplication2026
app.jwtExpirationMs=86400000

# Cloudinary Config
cloudinary.cloud_name=demo
cloudinary.api_key=your_api_key
cloudinary.api_secret=your_api_secret

server.port=8080
